#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GS_DIR="$REPO_ROOT/third_party/gaussian-splatting"

DATASET_NAME="${DATASET_NAME:-my_scene}"
DATASET_DIR="${DATASET_DIR:-$REPO_ROOT/data/$DATASET_NAME}"
INPUT_DIR="$DATASET_DIR/input"
RESULT_ROOT="${RESULT_ROOT:-$REPO_ROOT/results/$DATASET_NAME}"
OUTPUT_ROOT="${OUTPUT_ROOT:-$RESULT_ROOT/runs}"
LOG_DIR="$RESULT_ROOT/logs"
REPORT_DIR="$RESULT_ROOT/report_materials"

VIDEO_PATH="${VIDEO_PATH:-}"
IMAGE_DIR="${IMAGE_DIR:-}"
FPS="${FPS:-2}"
ITERATIONS="${ITERATIONS:-30000}"
RUN_SETUP="${RUN_SETUP:-1}"
RUN_COMPARISONS="${RUN_COMPARISONS:-0}"
COMPARISON_ITERATIONS="${COMPARISON_ITERATIONS:-7000}"
COLMAP_EXE="${COLMAP_EXE:-colmap}"
RESIZE="${RESIZE:-0}"
OVERWRITE_INPUT="${OVERWRITE_INPUT:-0}"
EXTRA_TRAIN_ARGS="${EXTRA_TRAIN_ARGS:-}"
DENSIFY_LOW_THRESHOLD="${DENSIFY_LOW_THRESHOLD:-0.0001}"
POS_LR_LOW="${POS_LR_LOW:-0.00008}"

usage() {
  cat <<'EOF'
Usage examples:

  # Full baseline run from a video. This also sets up the conda env by default.
  DATASET_NAME=my_scene VIDEO_PATH=/path/to/video.mp4 bash scripts/run_all_ubuntu.sh

  # Full baseline run from an existing image folder.
  DATASET_NAME=my_scene IMAGE_DIR=/path/to/images bash scripts/run_all_ubuntu.sh

  # Reuse existing data/<scene>/input and skip environment setup.
  DATASET_NAME=my_scene RUN_SETUP=0 bash scripts/run_all_ubuntu.sh

  # Run baseline plus three parameter-comparison runs for the report.
  DATASET_NAME=my_scene VIDEO_PATH=/path/to/video.mp4 RUN_COMPARISONS=1 bash scripts/run_all_ubuntu.sh

Important variables:
  DATASET_NAME           Scene name under data/ and results/. Default: my_scene
  VIDEO_PATH             Input video path. Optional if IMAGE_DIR or data/<scene>/input exists.
  IMAGE_DIR              Folder of input images. Optional if VIDEO_PATH or data/<scene>/input exists.
  FPS                    Video extraction FPS. Default: 2
  ITERATIONS             Baseline training iterations. Default: 30000
  RUN_SETUP              1 creates/updates env and CUDA extensions; 0 skips it. Default: 1
  RUN_COMPARISONS        1 runs iter_7000, densify_low, and pos_lr_low after baseline. Default: 0
  RESULT_ROOT            Final result folder. Default: results/<DATASET_NAME>
  OUTPUT_ROOT            Model run folder. Default: <RESULT_ROOT>/runs
  RESIZE                 1 passes --resize to convert.py. Default: 0
  OVERWRITE_INPUT        1 clears existing images in data/<scene>/input before copying/extracting. Default: 0
EOF
}

log() {
  printf '\n[%s] %s\n' "$(date '+%F %T')" "$*"
}

require_command() {
  local cmd="$1"
  local message="$2"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing command: $cmd" >&2
    echo "$message" >&2
    exit 1
  fi
}

count_input_images() {
  if [[ ! -d "$INPUT_DIR" ]]; then
    echo 0
    return
  fi
  find "$INPUT_DIR" -maxdepth 1 -type f \
    \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.tif' -o -iname '*.tiff' \) \
    | wc -l
}

make_result_dirs() {
  mkdir -p \
    "$OUTPUT_ROOT" \
    "$LOG_DIR" \
    "$REPORT_DIR/environment" \
    "$REPORT_DIR/dataset/input_samples" \
    "$REPORT_DIR/dataset/colmap" \
    "$REPORT_DIR/training" \
    "$REPORT_DIR/rendering" \
    "$REPORT_DIR/metrics" \
    "$REPORT_DIR/visualization/screenshots"

  cat > "$REPORT_DIR/README.md" <<EOF
# Report materials for $DATASET_NAME

This folder is generated by \`scripts/run_all_ubuntu.sh\`.

- \`environment/\`: environment check logs.
- \`dataset/\`: input samples and COLMAP file summaries.
- \`training/\`: training logs and commands.
- \`rendering/\`: render logs and sample render/ground-truth images.
- \`metrics/\`: metrics logs, \`results.json\`, and \`per_view.json\`.
- \`visualization/\`: point-cloud paths and screenshot placeholders.
- \`REPORT_CHECKLIST.md\`: checklist matched to the experiment-report requirements.
EOF

  cat > "$REPORT_DIR/visualization/screenshots/PUT_SCREENSHOTS_HERE.md" <<'EOF'
# Screenshots to place here manually

Suggested files:

- `supersplat_baseline.png`
- `supersplat_iter_7000.png`
- `supersplat_densify_low.png`
- `sibr_viewer.png` if SIBR is used
- terminal screenshots if the course requires image evidence instead of logs
EOF
}

clear_input_images() {
  if [[ "$OVERWRITE_INPUT" == "1" && -d "$INPUT_DIR" ]]; then
    log "Clearing existing input images in $INPUT_DIR"
    find "$INPUT_DIR" -maxdepth 1 -type f \
      \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.tif' -o -iname '*.tiff' \) \
      -delete
  fi
}

prepare_input_images() {
  mkdir -p "$INPUT_DIR" "$LOG_DIR"

  if [[ -n "$VIDEO_PATH" ]]; then
    if [[ ! -f "$VIDEO_PATH" ]]; then
      echo "VIDEO_PATH does not exist: $VIDEO_PATH" >&2
      exit 1
    fi
    require_command ffmpeg "Install FFmpeg, for example: sudo apt install -y ffmpeg"
    clear_input_images
    log "Extracting frames from $VIDEO_PATH at fps=$FPS"
    ffmpeg -y -i "$VIDEO_PATH" -vf "fps=$FPS" "$INPUT_DIR/%06d.jpg" 2>&1 | tee "$LOG_DIR/00_ffmpeg.log"
  elif [[ -n "$IMAGE_DIR" ]]; then
    if [[ ! -d "$IMAGE_DIR" ]]; then
      echo "IMAGE_DIR does not exist: $IMAGE_DIR" >&2
      exit 1
    fi
    clear_input_images
    log "Copying images from $IMAGE_DIR to $INPUT_DIR"
    local copied=0
    while IFS= read -r -d '' image_path; do
      cp "$image_path" "$INPUT_DIR/"
      copied=$((copied + 1))
    done < <(find "$IMAGE_DIR" -maxdepth 1 -type f \
      \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.tif' -o -iname '*.tiff' \) \
      -print0)
    echo "Copied $copied images." | tee "$LOG_DIR/00_copy_images.log"
  else
    log "No VIDEO_PATH or IMAGE_DIR set; trying existing $INPUT_DIR"
  fi

  local image_count
  image_count="$(count_input_images)"
  if [[ "$image_count" -eq 0 ]]; then
    echo "No input images found in $INPUT_DIR." >&2
    usage >&2
    exit 1
  fi
  log "Input image count: $image_count"

  find "$INPUT_DIR" -maxdepth 1 -type f \
    \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.tif' -o -iname '*.tiff' \) \
    | sort | head -n 6 | while IFS= read -r sample; do
      cp "$sample" "$REPORT_DIR/dataset/input_samples/"
    done
  find "$INPUT_DIR" -maxdepth 1 -type f \
    \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.tif' -o -iname '*.tiff' \) \
    | sort > "$REPORT_DIR/dataset/input_images.txt"
}

setup_environment() {
  cd "$REPO_ROOT"
  require_command git "Install Git, for example: sudo apt install -y git"

  if [[ "$RUN_SETUP" == "1" ]]; then
    log "Setting up gaussian_splatting environment and CUDA extensions"
    bash scripts/setup_gaussian_splatting_ubuntu.sh 2>&1 | tee "$LOG_DIR/01_setup.log"
  else
    log "Skipping environment setup because RUN_SETUP=0"
  fi

  require_command conda "Install Miniconda or load the server's conda module first."
  # shellcheck source=/dev/null
  source "$(conda info --base)/etc/profile.d/conda.sh"
  conda activate gaussian_splatting

  if ! command -v "$COLMAP_EXE" >/dev/null 2>&1; then
    echo "COLMAP executable not found: $COLMAP_EXE" >&2
    echo "Install it with apt/conda or set COLMAP_EXE=/absolute/path/to/colmap." >&2
    exit 1
  fi

  log "Environment check"
  python - <<'PY' 2>&1 | tee "$LOG_DIR/02_env_check.log"
import torch
print("torch:", torch.__version__)
print("torch cuda:", torch.version.cuda)
print("cuda available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("gpu:", torch.cuda.get_device_name(0))
import diff_gaussian_rasterization
import simple_knn._C
import fused_ssim
print("3DGS extensions import OK")
PY
  cp "$LOG_DIR/02_env_check.log" "$REPORT_DIR/environment/env_check.log"
}

convert_dataset() {
  log "Running COLMAP conversion"
  cd "$GS_DIR"
  local convert_args=(-s "$DATASET_DIR" --colmap_executable "$COLMAP_EXE")
  if [[ "$RESIZE" == "1" ]]; then
    convert_args+=(--resize)
  fi
  python convert.py "${convert_args[@]}" 2>&1 | tee "$LOG_DIR/03_convert.log"

  local sparse_dir="$DATASET_DIR/sparse/0"
  for file in cameras.bin images.bin points3D.bin; do
    if [[ ! -f "$sparse_dir/$file" ]]; then
      echo "COLMAP conversion did not produce $sparse_dir/$file" >&2
      exit 1
    fi
  done

  {
    echo "Dataset directory: $DATASET_DIR"
    echo "Input images: $(count_input_images)"
    echo
    echo "COLMAP sparse files:"
    ls -lh "$sparse_dir"
  } > "$REPORT_DIR/dataset/colmap/sparse_files.txt"
  cp "$LOG_DIR/03_convert.log" "$REPORT_DIR/dataset/colmap/convert.log"
}

copy_render_samples() {
  local run_id="$1"
  local model_dir="$2"
  local sample_dir="$REPORT_DIR/rendering/$run_id/sample_views"
  mkdir -p "$sample_dir/renders" "$sample_dir/gt"

  local method_dir=""
  if [[ -d "$model_dir/test" ]]; then
    method_dir="$(find "$model_dir/test" -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1 || true)"
  fi

  if [[ -n "$method_dir" && -d "$method_dir/renders" && -d "$method_dir/gt" ]]; then
    find "$method_dir/renders" -maxdepth 1 -type f | sort | head -n 3 | while IFS= read -r render_path; do
      local name
      name="$(basename "$render_path")"
      cp "$render_path" "$sample_dir/renders/$name"
      if [[ -f "$method_dir/gt/$name" ]]; then
        cp "$method_dir/gt/$name" "$sample_dir/gt/$name"
      fi
    done
    {
      echo "Run: $run_id"
      echo "Method directory: $method_dir"
      echo "Sample renders: $sample_dir/renders"
      echo "Sample ground truth: $sample_dir/gt"
    } > "$sample_dir/README.md"
  else
    echo "No test render directory found for $run_id. Check render log." > "$sample_dir/README.md"
  fi
}

collect_run_materials() {
  local run_id="$1"
  local iterations="$2"
  local model_dir="$3"

  mkdir -p \
    "$REPORT_DIR/training/$run_id" \
    "$REPORT_DIR/rendering/$run_id" \
    "$REPORT_DIR/metrics/$run_id" \
    "$REPORT_DIR/visualization/$run_id"

  cp "$LOG_DIR/04_${run_id}_train.log" "$REPORT_DIR/training/$run_id/train.log"
  cp "$LOG_DIR/05_${run_id}_render.log" "$REPORT_DIR/rendering/$run_id/render.log"
  cp "$LOG_DIR/06_${run_id}_metrics.log" "$REPORT_DIR/metrics/$run_id/metrics.log"

  if [[ -f "$model_dir/results.json" ]]; then
    cp "$model_dir/results.json" "$REPORT_DIR/metrics/$run_id/results.json"
  fi
  if [[ -f "$model_dir/per_view.json" ]]; then
    cp "$model_dir/per_view.json" "$REPORT_DIR/metrics/$run_id/per_view.json"
  fi

  local point_cloud="$model_dir/point_cloud/iteration_${iterations}/point_cloud.ply"
  {
    echo "Run: $run_id"
    echo "Point cloud for SuperSplat:"
    echo "$point_cloud"
    echo
    echo "Open https://superspl.at/editor and import the file above."
  } > "$REPORT_DIR/visualization/$run_id/point_cloud_path.txt"

  copy_render_samples "$run_id" "$model_dir"
}

train_render_metrics() {
  local run_id="$1"
  local iterations="$2"
  shift 2

  local model_dir="$OUTPUT_ROOT/$run_id"
  mkdir -p "$model_dir"
  cd "$GS_DIR"

  log "Training run: $run_id"
  {
    echo "python train.py -s $DATASET_DIR -m $model_dir --eval --iterations $iterations $*"
  } > "$REPORT_DIR/training/${run_id}_command.txt"
  python train.py \
    -s "$DATASET_DIR" \
    -m "$model_dir" \
    --eval \
    --iterations "$iterations" \
    "$@" 2>&1 | tee "$LOG_DIR/04_${run_id}_train.log"

  log "Rendering run: $run_id"
  python render.py -m "$model_dir" 2>&1 | tee "$LOG_DIR/05_${run_id}_render.log"

  log "Metrics run: $run_id"
  python metrics.py -m "$model_dir" 2>&1 | tee "$LOG_DIR/06_${run_id}_metrics.log"

  collect_run_materials "$run_id" "$iterations" "$model_dir"
}

write_report_checklist() {
  local checklist="$REPORT_DIR/REPORT_CHECKLIST.md"
  cat > "$checklist" <<EOF
# 3DGS experiment report checklist

## 1. Environment evidence

- [x] Environment check log: \`$REPORT_DIR/environment/env_check.log\`
- [ ] Screenshot of \`nvidia-smi\`, CUDA/PyTorch check, or terminal environment verification.

## 2. Dataset preparation

- [x] Input image list: \`$REPORT_DIR/dataset/input_images.txt\`
- [x] Input image samples: \`$REPORT_DIR/dataset/input_samples/\`
- [x] COLMAP conversion log: \`$REPORT_DIR/dataset/colmap/convert.log\`
- [x] COLMAP sparse file summary: \`$REPORT_DIR/dataset/colmap/sparse_files.txt\`
- [ ] Screenshot of COLMAP sparse point cloud or dataset directory tree.

## 3. Training process

- [x] Baseline train log: \`$REPORT_DIR/training/baseline/train.log\`
- [x] Baseline model folder: \`$OUTPUT_ROOT/baseline\`
- [ ] Loss/PSNR trend screenshot or manually plotted curve from training log.

## 4. Rendering and metrics

- [x] Baseline render log: \`$REPORT_DIR/rendering/baseline/render.log\`
- [x] Baseline sample render/GT images: \`$REPORT_DIR/rendering/baseline/sample_views/\`
- [x] Baseline metrics log: \`$REPORT_DIR/metrics/baseline/metrics.log\`
- [x] Baseline aggregate metrics if generated: \`$REPORT_DIR/metrics/baseline/results.json\`
- [x] Baseline per-view metrics if generated: \`$REPORT_DIR/metrics/baseline/per_view.json\`
- [ ] Select at least 3 test views and put render-vs-GT comparisons into the report.

## 5. Visualization

- [x] Baseline SuperSplat point cloud path: \`$REPORT_DIR/visualization/baseline/point_cloud_path.txt\`
- [ ] SuperSplat screenshot saved under \`$REPORT_DIR/visualization/screenshots/\`
- [ ] SIBR screenshot if SIBR is used.

## 6. Parameter comparison

- [ ] At least two comparison runs completed. Set \`RUN_COMPARISONS=1\` to generate \`iter_7000\`, \`densify_low\`, and \`pos_lr_low\`.
- [ ] Fill the comparison table in \`experiments/params.example.csv\` or the report.
- [ ] Explain quality, speed, PSNR/SSIM, and Gaussian-count differences.

## 7. Principle analysis

- [ ] Explain 3D Gaussian scene representation.
- [ ] Explain differentiable rasterization.
- [ ] Explain density control.
- [ ] Compare 3DGS with NeRF or other related methods.
- [ ] Discuss why COLMAP quality affects final reconstruction.
EOF
}

write_summary() {
  local summary="$RESULT_ROOT/RUN_SUMMARY.md"
  cat > "$summary" <<EOF
# 3DGS Run Summary

- Dataset: \`$DATASET_NAME\`
- Dataset directory: \`$DATASET_DIR\`
- Result directory: \`$RESULT_ROOT\`
- Model runs directory: \`$OUTPUT_ROOT\`
- Input images: \`$(count_input_images)\`
- Baseline iterations: \`$ITERATIONS\`
- Run comparisons: \`$RUN_COMPARISONS\`
- Logs: \`$LOG_DIR\`
- Report materials: \`$REPORT_DIR\`

## Important outputs

- Baseline model: \`$OUTPUT_ROOT/baseline\`
- Baseline point cloud: \`$OUTPUT_ROOT/baseline/point_cloud/iteration_${ITERATIONS}/point_cloud.ply\`
- Baseline metrics: \`$REPORT_DIR/metrics/baseline/results.json\`
- Baseline per-view metrics: \`$REPORT_DIR/metrics/baseline/per_view.json\`
- Report checklist: \`$REPORT_DIR/REPORT_CHECKLIST.md\`
- SuperSplat: https://superspl.at/editor

## Reproduce command

\`\`\`bash
DATASET_NAME=$DATASET_NAME \\
VIDEO_PATH=$VIDEO_PATH \\
IMAGE_DIR=$IMAGE_DIR \\
FPS=$FPS \\
ITERATIONS=$ITERATIONS \\
RUN_SETUP=$RUN_SETUP \\
RUN_COMPARISONS=$RUN_COMPARISONS \\
RESULT_ROOT=$RESULT_ROOT \\
bash scripts/run_all_ubuntu.sh
\`\`\`
EOF
  log "Summary written to $summary"
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

make_result_dirs

log "Starting 3DGS full pipeline"
prepare_input_images
setup_environment
convert_dataset

# shellcheck disable=SC2206
EXTRA_ARGS=($EXTRA_TRAIN_ARGS)
train_render_metrics "baseline" "$ITERATIONS" "${EXTRA_ARGS[@]}"

if [[ "$RUN_COMPARISONS" == "1" ]]; then
  train_render_metrics "iter_${COMPARISON_ITERATIONS}" "$COMPARISON_ITERATIONS"
  train_render_metrics "densify_low" "$ITERATIONS" --densify_grad_threshold "$DENSIFY_LOW_THRESHOLD"
  train_render_metrics "pos_lr_low" "$ITERATIONS" --position_lr_init "$POS_LR_LOW"
fi

write_report_checklist
write_summary
log "Done"
